import pytest

from wfrp.character.data.armour import ARMOUR_DATA
from wfrp.character.data.careers.careers import CAREER_DATA
from wfrp.character.data.careers.seafarer import SEAFARER_CLASS_DATA
from wfrp.character.data.class_trappings import get_class_trappings
from wfrp.character.data.trappings import TRAPPINGS_DATA
from wfrp.character.data.weapons import WEAPONS_DATA

IGNORE_OR_TRAPPINGS = [
    "2 Riverboats or 4 Wagons",
    "Assistant (Student or Servant)",
    "Blue or Green or Turquoise Robes",
    "Flail or Great Weapon",
    "Great Weapon or Halberd",
    "Hand Weapon or Bow with 10 arrows",
    "Hut or Riverboat",
    "Large Unit of Knights or Several Small Units of Knights",
    "Mask or Scarves",
    "Net or Whip",
    "Quality Foil or Hand Mirror",
    "Riding Horse with Saddle and Harness or Coach",
    "Riverboat or 2 Wagons",
]

IGNORE_TRAPPINGS = [
    "Assortment of Animal Skulls",
    "Dragon’s Head",
    "Giant’s Head",
    "Lucky Charm",
    "Opinions",
    "Orders",
    "Seal of Office",
    "Shame",
    "Skull",
    "The Respect of the Village",
    "Troll’s Head",
]

# real estate
IGNORE_TRAPPINGS += [
    "A Fleet",
    "Abbey",
    "Access to a Library",
    "Cabin",
    "Fiefdom",
    "Fleet of Coaches and Horses",
    "Fleet of Riverboats and Wrecker Crew",
    "Flotilla of Ships",
    "Governor’s Residence",
    "Guild",
    "Hiding Place",
    "Hut",
    "Isolated Hut",
    "Kennel of Hunting Dogs",
    "Lair",
    "Large Town Estate",
    "Large Townhouse with Gardens and Servants",
    "Livery",
    "Lodgings",
    "Loft of Homing Pigeons",
    "Modest Townhouse",
    "Office",
    "Office and Staff",
    "Pawnbroker’s Shop",
    "Province",
    "Study",
    "Temple",
    "Town House with Servants",
    "Townhouse",
    "Townhouse with Discreet Back Entrance",
    "Village Home and Workshop",
    "Wardrobe of Costumes and Props",
    "Warehouse",
    "Wreck Dwelling",
]

# hirelings
IGNORE_TRAPPINGS += [
    "A Ring of Hustlers",
    "Aide",
    "Apprentice",
    "Assistant",
    "Bailiff",
    "Band of Outlaws",
    "Boathand",
    "Coach and Driver",
    "Coach and Footman",
    "Couriers",
    "Crew",
    "Crew of Miners",
    "Followers (including Penitents, Flagellants, and Zealots)",
    "Gang of Stevedores",
    "Gang of Thugs and Racketeers",
    "Herald",
    "Herb Gatherer",
    "Hired Muscle",
    "Informer",
    "Network of Informants",
    "Network of Informers",
    "Pamphleteer",
    "Patrol Boats and Crew",
    "Patron",
    "Pauper Follower",
    "Personal Servant",
    "Ring of Informers",
    "Ring of Spies and Informers",
    "River Runner",
    "Sailing Ship and Crew",
    "Servant",
    "Spies, and Informers",
    "Squad of Road Wardens",
    "Squire",
    "Staff of Advisors and Aides",
    "Staff of Diplomats",
    "Staff of Wardens and Custodians",
    "Troupe of Entertainers",
    "Trusty Second",
    "Unit of Road Wardens",
    "Unit of Soldiers",
    "Unit of Troops",
    "a Ring of Bawds",
    "‘Fiefdom’ of Outlaw Chiefs",
]

IGNORE_TRAPPINGS += [
    "1 Forged Document",
    "10 sheets of parchment",
    "100 GC",
    "1000 GC",
    "2 Barrels",
    "2 Quality Weapons",
    "2 Sets of Clothing",
    "2 Sets of Quality Clothing",
    "2 Warehouses",
    "2 Wooden Training Swords",
    "2 rags",
    "2 sets of Quality Courtly Garb",
    "20 GC",
    "20 Silver Shillings",
    "200 GC",
    "3 Apprentices",
    "3 Bandages",
    "3 Healing Poultices",
    "3 Pamphleteers",
    "3 Tax Collectors",
    "4 Household Servants",
    "4 Pairs of Manacles",
    "4 sets of Best Quality Courtly Garb",
    "50 Silver in Coin",
    "500 GC",
    "6 Lucky Charms",
    "Alcohol",
    "Animal Traps",
    "Bandages",
    "Barding",
    "Best Quality Courtly Clothes",
    "Best Quality Courtly Garb",
    "Big Hat",
    "Blunderbuss with 10 Shots",
    "Boat",
    "Boat to Command",
    "Book",
    "Book (Blank)",
    "Bow and 10 Arrows",
    "Bow with 10 Arrows",
    "Bow with 10 arrows",
    "Brush",
    "Candles",
    "Canvas Tarpaulin",
    "Captain’s Log",
    "Ceremonial Boat",
    "Ceremonial Cloak and Garland",
    "Ceremonial Robes",
    "Ceremonial Staff of Office",
    "Chains of Office",
    "Charcoal Stick",
    "Cheap Jewellery",
    "Cloak with Several Pockets",
    "Coach Horn",
    "Commission Papers",
    "Copper Badge",
    "Court Robes",
    "Courtly Attire",
    "Crossbow Pistol with 10 Bolts",
    "Crossbow and 10 bolts",
    "Crossbow with 10 Bolts",
    "Crossbow with 10 shots",
    "Crude Map",
    "Cutlass",
    "Dark Clothing",
    "Degree",
    "Destrier with Saddle and Tack",
    "Dose of Weirdroot",
    "Draught Horse and Cart",
    "Draught Horse and Wagon",
    "Draught Horses and Wagon (Stage)",
    "Eel Trap",
    "Eye-glass",
    "Fine Clothes",
    "Fishing Net",
    "Fishing Rod and Bait",
    "Flask of Spirits",
    "Forged Seal",
    "Found Boots",
    "Garotte",
    "Goods worth 18 Brass",
    "Goods worth 2d10 Silver",
    "Goods worth at least 2d10 Gold",
    "Goods worth at least 5d10 Gold",
    "Grappling Hook and Rope",
    "Great Weapon (Two-handed Pick)",
    "Grimoire",
    "Hammer and Nails",
    "Hammer and Spikes",
    "Hammock",
    "Hand Weapon (Axe)",
    "Hand Weapon (Boat Hook)",
    "Hand Weapon (Pick)",
    "Hand Weapon (Sickle)",
    "Hand Weapon: Sword",
    "Handcart",
    "Hat (Henin)",
    "Helmet",
    "Holy Book of Manann",
    "Holy Relic",
    "Hooded Cloak",
    "Horse and Cart",
    "Horse with Saddle and Tack",
    "Impressive Hat",
    "Instruments of Torture",
    "Jewellery worth 16 GC",
    "Jewellery worth 200 GC",
    "Jewellery worth 50 GC",
    "Jewellery worth 500 GC",
    "Journal",
    "Keg of Ale",
    "Keys",
    "Lantern and Oil",
    "Lantern and Pole",
    "Large Group of Beggar Followers",
    "Large Sack",
    "Large Spy Ring of Agents",
    "Large Workshop",
    "Large Workshop (Artist)",
    "Large Workshop (Engineer)",
    "Large and Vicious Dog",
    "Leather Gloves",
    "Letter of Appointment",
    "Letter of Commission",
    "Library (Art)",
    "Library (Engineer)",
    "Library (Law)",
    "Library (Magic)",
    "Library (Theology)",
    "Light Warhorse with Saddle and Tack",
    "Magical Item",
    "Magical Licence",
    "Magnifying Glass",
    "Maps",
    "Melee Weapon (Any)",
    "Mortarboard",
    "Mule and Cart",
    "Mule and Saddlebags",
    "Multiple Forged Documents",
    "Musical Instrument",
    "Net",
    "Ostentatious Wig",
    "Pile of Leaflets",
    "Pins",
    "Pistol with 10 Shots",
    "Pistol with 10 shot",
    "Pistol with Gunpowder and Ammunition",
    "Plate Armour and Helm",
    "Plumed Great Helm",
    "Poison",
    "Pole",
    "Pole for Dead Rats",
    "Pony and Cart",
    "Poor Quality Blanket",
    "Porter Cap",
    "Printing Press",
    "Quality Cloak",
    "Quality Clothes",
    "Quality Clothing",
    "Quality Clothing and Hat",
    "Quality Courtly Garb",
    "Quality Hand weapon",
    "Quality Hat",
    "Quality Hat and Cloak",
    "Quality Helmet",
    "Quality Instrument",
    "Quality Livery",
    "Quality Rapier",
    "Quality Robes",
    "Quality Symbol of Rank",
    "Quality Trade Tools (Engineer)",
    "Quality Uniform",
    "Quill and Ink",
    "Rain Hat",
    "Religious Order",
    "Religious Relic",
    "Riding Horse and Saddle",
    "Riding Horse with Saddle and Harness",
    "Riding Horse with Saddle and Tack",
    "Riverboat",
    "Riverboat and Crew",
    "Sack of Poisoned Bait (10 doses of Heartkill)",
    "Saddlebags with 2 weeks’ Rations",
    "Sash",
    "Sea Chest",
    "Sealskin Coat",
    "Selection of Amulets",
    "Selection of Animal Traps",
    "Selection of Coloured Powders and Water",
    "Selection of Herbs",
    "Selection of Maps",
    "Selection of Pots and Pans",
    "Selection of Scripts (that you can’t yet read)",
    "Selection of Trinkets and Charms",
    "Sextant",
    "Shipping Charts",
    "Ship’s Chest",
    "Silvered Sword",
    "Sleeved Mail Shirt",
    "Sling Bag containing 2 different sets of clothing and Hooded Cloak",
    "Sling Bag containing Assortment of Herbs",
    "Sling Bag containing Clothing",
    "Sling Bag containing Trade Tools (Artist)",
    "Sling with 10 Stone Bullets",
    "Sling with Ammunition",
    "Small Boat",
    "Small Fleet of Riverboats",
    "Small Riverboat",
    "Small Unit of Knights",
    "Small but Vicious Dog",
    "Speedy Riverboat",
    "Spyglass",
    "Stolen Goods worth 8 Shillings",
    "Storm Lantern and Oil",
    "Storm Lantern with Oil",
    "String Bag",
    "Sturdy Boots",
    "Sturdy Boots and Cloak",
    "Subordinate Gang Bosses",
    "Subordinate High Priests",
    "Subordinate Interrogators",
    "Subordinate Priests",
    "Subordinate Witch Hunters",
    "Symbol of Manann",
    "Symbol of Rank",
    "Tarpaulin",
    "Tattered Robes",
    "Tattoos",
    "Throwing Axes",
    "Throwing Knives",
    "Throwing Weapons",
    "Tools",
    "Trade Tools (Any)",
    "Trade Tools (Astrology)",
    "Trade Tools (Carpenter)",
    "Trade Tools (Cartographer)",
    "Trade Tools (Engineer)",
    "Trade Tools (Engraver)",
    "Trade Tools (Farrier)",
    "Trade Tools (Herbalist)",
    "Trade Tools (Medicine)",
    "Trade Tools (Thief)",
    "Trade Tools (Tinker)",
    "Trade Tools (Writing)",
    "Trade Tools (as Trade)",
    "Trained Animal",
    "Trident (counts as Spear)",
    "Warm Coat and Gloves",
    "Warrant Papers",
    "Weapon (Any Melee)",
    "Weapon (Any)",
    "Whistle",
    "Workshop (Artist)",
    "Workshop (Herbalist)",
    "Workshop (Magic)",
    "Workshop (Medicine)",
    "small lock box",
]


def check_item_exists(trapping):
    if trapping in WEAPONS_DATA:
        return True
    if trapping in ARMOUR_DATA:
        return True
    if trapping in TRAPPINGS_DATA:
        return True
    if trapping in IGNORE_TRAPPINGS:
        return True
    return False


@pytest.mark.data
@pytest.mark.parametrize(
    "career_class",
    [
        "Academics",
        "Burghers",
        "Courtiers",
        "Peasants",
        "Rangers",
        "Riverfolk",
        "Rogues",
        "Seafarer",
        "Warriors",
    ],
)
def test_class_trappings(career_class):
    for trapping in get_class_trappings(career_class):
        for trapping in trapping.split(" or "):
            if " ".join(trapping.split()[1:]) in [
                "sheets of Parchment",
                "Matches",
                "Candles",
            ]:
                continue
            assert check_item_exists(trapping)


@pytest.mark.data
def test_seafarer_career_trappings():
    for career in SEAFARER_CLASS_DATA:
        for level in SEAFARER_CLASS_DATA[career]:
            trappings = SEAFARER_CLASS_DATA[career][level]["trappings"]
            for trapping in trappings:
                if trapping in IGNORE_OR_TRAPPINGS:
                    continue
                assert check_item_exists(trapping)


@pytest.mark.data
# @pytest.mark.xfail(reason="Not complete")
def test_career_trappings():
    missing = []
    for career in CAREER_DATA:
        for level in CAREER_DATA[career]:
            trappings = CAREER_DATA[career][level]["trappings"]
            for trapping in trappings:
                if trapping in IGNORE_OR_TRAPPINGS:
                    continue
                for trapping in trapping.split(" or "):
                    if not check_item_exists(trapping) and trapping not in missing:
                        missing.append(trapping)
    for career in SEAFARER_CLASS_DATA:
        for level in SEAFARER_CLASS_DATA[career]:
            trappings = SEAFARER_CLASS_DATA[career][level]["trappings"]
            for trapping in trappings:
                if trapping in IGNORE_OR_TRAPPINGS:
                    continue
                if not check_item_exists(trapping) and trapping not in missing:
                    missing.append(trapping)
    if missing:
        breakpoint()
        raise AssertionError(f"Not Found: {missing}")
