from wfrp.character.utils import roll_2d10
from wfrp.character.utils import roll_3d10
from wfrp.character.utils import roll_d10


def list_careers(species=None):
    if species is None:
        return list(CAREER_DATA.keys())
    if species == "Human":
        return list(HUMAN_CAREERS.values())
    elif species == "Halfling":
        return list(HALFLING_CAREERS.values())
    elif species == "Dwarf":
        return list(DWARF_CAREERS.values())
    elif species == "High Elf":
        return list(HIGH_ELF_CAREERS.values())
    elif species == "Wood Elf":
        return list(WOOD_ELF_CAREERS.values())
    raise NotImplementedError("Invalid species sent to list careers")


def get_career(species, die_roll):
    if species == "Human":
        career_list = HUMAN_CAREERS
    elif species == "Halfling":
        career_list = HALFLING_CAREERS
    elif species == "Dwarf":
        career_list = DWARF_CAREERS
    elif species == "High Elf":
        career_list = HIGH_ELF_CAREERS
    elif species == "Wood Elf":
        career_list = WOOD_ELF_CAREERS
    else:
        raise NotImplementedError("Invalid species sent to get career")
    while True:
        try:
            return career_list[die_roll]
        except KeyError:
            die_roll += 1


HUMAN_CAREERS = {
    1: "Apothecary",
    2: "Engineer",
    3: "Lawyer",
    5: "Nun",
    6: "Physician",
    11: "Priest",
    13: "Scholar",
    14: "Wizard",
    15: "Agitator",
    17: "Artisan",
    19: "Beggar",
    20: "Investigator",
    21: "Merchant",
    23: "Rat Catcher",
    26: "Townsman",
    27: "Watchman",
    28: "Advisor",
    29: "Artist",
    30: "Duellist",
    31: "Envoy",
    32: "Noble",
    35: "Servant",
    36: "Spy",
    37: "Warden",
    38: "Bailiff",
    39: "Hedge Witch",
    40: "Herbalist",
    42: "Hunter",
    43: "Miner",
    44: "Mystic",
    45: "Scout",
    50: "Villager",
    51: "Bounty Hunter",
    52: "Coachman",
    54: "Entertainer",
    56: "Flagellant",
    57: "Messenger",
    58: "Pedlar",
    59: "Road Warden",
    60: "Witch Hunter",
    62: "Boatman",
    63: "Huffer",
    65: "Riverwarden",
    68: "Riverwoman",
    70: "Seaman",
    71: "Smuggler",
    73: "Stevedore",
    74: "Wrecker",
    76: "Bawd",
    77: "Charlatan",
    78: "Fence",
    79: "Grave Robber",
    83: "Outlaw",
    84: "Racketeer",
    87: "Thief",
    88: "Witch",
    90: "Cavalryman",
    92: "Guard",
    93: "Knight",
    94: "Pit Fighter",
    95: "Protagonist",
    99: "Soldier",
    100: "Warrior Priest",
}

DWARF_CAREERS = {
    1: "Apothecary",
    4: "Engineer",
    6: "Lawyer",
    7: "Physician",
    9: "Scholar",
    11: "Agitator",
    17: "Artisan",
    18: "Beggar",
    20: "Investigator",
    24: "Merchant",
    25: "Rat Catcher",
    31: "Townsman",
    34: "Watchman",
    36: "Advisor",
    37: "Artist",
    38: "Duellist",
    40: "Envoy",
    41: "Noble",
    42: "Servant",
    43: "Spy",
    45: "Warden",
    47: "Bailiff",
    49: "Hunter",
    54: "Miner",
    55: "Scout",
    56: "Villager",
    60: "Bounty Hunter",
    61: "Coachman",
    63: "Entertainer",
    65: "Messenger",
    67: "Pedlar",
    69: "Boatman",
    70: "Huffer",
    72: "Riverwoman",
    73: "Seaman",
    75: "Smuggler",
    77: "Stevedore",
    78: "Wrecker",
    79: "Fence",
    82: "Outlaw",
    83: "Racketeer",
    84: "Thief",
    87: "Guard",
    90: "Pit Fighter",
    93: "Protagonist",
    96: "Soldier",
    100: "Slayer",
}

HALFLING_CAREERS = {
    1: "Apothecary",
    2: "Engineer",
    4: "Lawyer",
    6: "Physician",
    8: "Scholar",
    10: "Agitator",
    15: "Artisan",
    19: "Beggar",
    21: "Investigator",
    25: "Merchant",
    28: "Rat Catcher",
    31: "Townsman",
    33: "Watchman",
    34: "Advisor",
    36: "Artist",
    37: "Envoy",
    43: "Servant",
    44: "Spy",
    46: "Warden",
    47: "Bailiff",
    50: "Herbalist",
    52: "Hunter",
    53: "Miner",
    54: "Scout",
    57: "Villager",
    58: "Bounty Hunter",
    60: "Coachman",
    63: "Entertainer",
    65: "Messenger",
    67: "Pedlar",
    68: "Road Warden",
    69: "Boatman",
    70: "Huffer",
    71: "Riverwarden",
    74: "Riverwoman",
    75: "Seaman",
    79: "Smuggler",
    82: "Stevedore",
    85: "Bawd",
    86: "Charlatan",
    87: "Fence",
    88: "Grave Robber",
    89: "Outlaw",
    90: "Racketeer",
    94: "Thief",
    96: "Guard",
    97: "Pit Fighter",
    100: "Soldier",
}

HIGH_ELF_CAREERS = {
    2: "Apothecary",
    6: "Lawyer",
    8: "Physician",
    12: "Scholar",
    16: "Wizard",
    19: "Artisan",
    21: "Investigator",
    26: "Merchant",
    28: "Townsman",
    29: "Watchman",
    31: "Advisor",
    32: "Artist",
    34: "Duellist",
    37: "Envoy",
    40: "Noble",
    43: "Spy",
    45: "Warden",
    47: "Herbalist",
    50: "Hunter",
    56: "Scout",
    59: "Bounty Hunter",
    62: "Entertainer",
    63: "Messenger",
    64: "Boatman",
    79: "Seaman",
    80: "Smuggler",
    82: "Bawd",
    85: "Charlatan",
    88: "Outlaw",
    92: "Cavalryman",
    94: "Guard",
    95: "Knight",
    97: "Pit Fighter",
    98: "Protagonist",
    100: "Soldier",
}

WOOD_ELF_CAREERS = {
    1: "Scholar",
    5: "Wizard",
    10: "Artisan",
    14: "Advisor",
    18: "Artist",
    25: "Envoy",
    31: "Noble",
    35: "Spy",
    42: "Herbalist",
    52: "Hunter",
    57: "Mystic",
    68: "Scout",
    70: "Bounty Hunter",
    75: "Entertainer",
    78: "Messenger",
    79: "Wrecker",
    85: "Outlaw",
    90: "Cavalryman",
    92: "Guard",
    94: "Knight",
    96: "Pit Fighter",
    100: "Soldier",
}

CAREER_DATA = {
    # Academics
    "Apothecary": {
        "class": "Academics",
        "Apothecary’s Apprentice": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Toughness", "Dexterity", "Intelligence"],
            "skills": [
                "Consume Alcohol",
                "Heal",
                "Language (Classical)",
                "Lore (Chemistry)",
                "Lore (Medicine)",
                "Lore (Plants)",
                "Trade (Apothecary)",
                "Trade (Poisoner)",
            ],
            "talents": [
                "Concoct",
                "Craftsman (Apothecary)",
                "Etiquette (Scholar)",
                "Read/Write",
            ],
            "trappings": [
                "Book (Blank)",
                "Healing Draught",
                "Leather Jerkin",
                "Pestle and Mortar",
            ],
        },
    },
    "Engineer": {
        "class": "Academics",
        "Student Engineer": {
            "status": {"tier": "Brass", "standing": 4},
            "attributes": ["Ballistic Skill", "Dexterity", "Intelligence"],
            "skills": [
                "Consume Alcohol",
                "Cool",
                "Endurance",
                "Language (Classical)",
                "Lore (Engineer)",
                "Perception",
                "Ranged (Blackpowder)",
                "Trade (Engineer)",
            ],
            "talents": [
                "Artistic",
                "Gunner",
                "Read/Write",
                "Tinker",
            ],
            "trappings": [
                "Book (Engineer)",
                "Hammer and Spikes",
            ],
        },
    },
    "Lawyer": {
        "class": "Academics",
        "Student Lawyer": {
            "status": {"tier": "Brass", "standing": 4},
            "attributes": ["Initiative", "Dexterity", "Intelligence"],
            "skills": [
                "Consume Alcohol",
                "Endurance",
                "Haggle",
                "Language (Classical)",
                "Lore (Law)",
                "Lore (Theology)",
                "Perception",
                "Research",
            ],
            "talents": [
                "Blather",
                "Etiquette (Scholar)",
                "Read/Write",
                "Speedreader",
            ],
            "trappings": [
                "Book (Law)",
                "Magnifying Glass",
            ],
        },
    },
    "Nun": {
        "class": "Academics",
        "Novitiate": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Dexterity", "Intelligence", "Fellowship"],
            "skills": [
                "Art (Calligraphy)",
                "Cool",
                "Endurance",
                "Entertain (Storyteller)",
                "Gossip",
                "Heal",
                "Lore (Theology)",
                "Pray",
            ],
            "talents": [
                "Bless (Any)",
                "Stone Soup",
                "Panhandle",
                "Read/Write",
            ],
            "trappings": [
                "Religious Symbol",
                "Robes",
            ],
        },
    },
    "Physician": {
        "class": "Academics",
        "Physician’s Apprentice": {
            "status": {"tier": "Brass", "standing": 4},
            "attributes": ["Dexterity", "Intelligence", "Willpower"],
            "skills": [
                "Bribery",
                "Cool",
                "Drive",
                "Endurance",
                "Gossip",
                "Heal",
                "Perception",
                "Sleight of Hand",
            ],
            "talents": [
                "Bookish",
                "Field Dressing",
                "Read/Write",
                "Strike to Stun",
            ],
            "trappings": [
                "Bandages",
                "Healing Draught",
            ],
        },
    },
    "Priest": {
        "class": "Academics",
        "Initiate": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Toughness", "Agility", "Willpower"],
            "skills": [
                "Athletics",
                "Cool",
                "Endurance",
                "Intuition",
                "Lore (Theology)",
                "Perception",
                "Pray",
                "Research",
            ],
            "talents": [
                "Bless (Any)",
                "Holy Visions",
                "Read/Write",
                "Suave",
            ],
            "trappings": [
                "Religious Symbol",
                "Robes",
            ],
        },
    },
    "Scholar": {
        "class": "Academics",
        "Student": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Toughness", "Intelligence", "Willpower"],
            "skills": [
                "Consume Alcohol",
                "Entertain (Storytelling)",
                "Gamble",
                "Gossip",
                "Haggle",
                "Language (Classical)",
                "Lore (Any)",
                "Research",
            ],
            "talents": [
                "Carouser",
                "Read/Write",
                "Savvy",
                "Super Numerate",
            ],
            "trappings": [
                "Alcohol",
                "Book",
                "Opinions",
                "Writing Kit",
            ],
        },
    },
    "Wizard": {
        "class": "Academics",
        "Wizard’s Apprentice": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Weapon Skill", "Intelligence", "Willpower"],
            "skills": [
                "Channelling (Any Colour)",
                "Dodge",
                "Intuition",
                "Language (Magick)",
                "Lore (Magic)",
                "Melee (Basic)",
                "Melee (Polearm)",
                "Perception",
            ],
            "talents": [
                "Aethyric Attunement",
                "Petty Magic",
                "Read/Write",
                "Second Sight",
            ],
            "trappings": [
                "Grimoire",
                "Quarterstaff",
            ],
        },
    },
    # Burghers
    "Agitator": {
        "class": "Burghers",
        "Pamphleteer": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Ballistic Skill", "Intelligence", "Fellowship"],
            "skills": [
                "Art (Writing)",
                "Bribery",
                "Charm",
                "Consume Alcohol",
                "Gossip",
                "Haggle",
                "Lore (Politics)",
                "Trade (Printing)",
            ],
            "talents": [
                "Blather",
                "Gregarious",
                "Panhandle",
                "Read/Write",
            ],
            "trappings": [
                "Writing Kit",
                "Hammer and Nails",
                "Pile of Leaflets",
            ],
        },
    },
    "Artisan": {
        "class": "Burghers",
        "Apprentice Artisan": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Strength", "Toughness", "Dexterity"],
            "skills": [
                "Athletics",
                "Cool",
                "Consume Alcohol",
                "Dodge",
                "Endurance",
                "Evaluate",
                "Stealth (Urban)",
                "Trade (Any)",
            ],
            "talents": [
                "Artistic",
                "Craftsman (Any)",
                "Strong Back",
                "Very Strong",
            ],
            "trappings": [
                "Chalk",
                "Leather Jerkin",
                f"{roll_d10()} rags",
            ],
        },
    },
    "Beggar": {
        "class": "Burghers",
        "Pauper": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["Toughness", "Agility", "Fellowship"],
            "skills": [
                "Athletics",
                "Charm",
                "Consume Alcohol",
                "Cool",
                "Dodge",
                "Endurance",
                "Intuition",
                "Stealth (Urban)",
            ],
            "talents": [
                "Panhandle",
                "Resistance (Disease)",
                "Stone Soup",
                "Very Resilient",
            ],
            "trappings": [
                "Poor Quality Blanket",
                "Cup",
            ],
        },
    },
    "Investigator": {
        "class": "Burghers",
        "Sleuth": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["", "", ""],
            "skills": [
                "Charm",
                "Climb",
                "Cool",
                "Gossip",
                "Intuition",
                "Perception",
                "Stealth (Urban)",
                "Track",
            ],
            "talents": [
                "Alley Cat",
                "Beneath Notice",
                "Read/Write",
                "Sharp",
            ],
            "trappings": [
                "Lantern",
                "Lamp Oil,",
                "Journal",
                "Quill and Ink",
            ],
        },
    },
    "Merchant": {
        "class": "Burghers",
        "Trader": {
            "status": {"tier": "Silver", "standing": 2},
            "attributes": ["Agility", "Willpower", "Fellowship"],
            "skills": [
                "Animal Care",
                "Bribery",
                "Charm",
                "Consume Alcohol",
                "Drive",
                "Gamble",
                "Gossip",
                "Haggle",
            ],
            "talents": [
                "Blather",
                "Dealmaker",
                "Read/Write",
                "Suave",
            ],
            "trappings": [
                "Abacus",
                "Mule and Cart",
                "Canvas Tarpaulin",
                f"{roll_3d10()} Silver Shillings",
            ],
        },
    },
    "Rat Catcher": {
        "class": "Burghers",
        "Rat Hunter": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Weapon Skill", "Ballistic Skill", "Willpower"],
            "skills": [
                "Athletics",
                "Animal Training (Dog)",
                "Charm Animal",
                "Consume Alcohol",
                "Endurance",
                "Melee (Basic)",
                "Ranged (Sling)",
                "Stealth (Underground or Urban)",
            ],
            "talents": [
                "Night Vision",
                "Resistance (Disease)",
                "Strike Mighty Blow",
                "Strike to Stun",
            ],
            "trappings": [
                "Sling with Ammunition",
                "Sack",
                "Small but Vicious Dog",
            ],
        },
    },
    "Townsman": {
        "class": "Burghers",
        "Clerk": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Agility", "Intelligence", "Fellowship"],
            "skills": [
                "Charm",
                "Climb",
                "Consume Alcohol",
                "Drive",
                "Dodge",
                "Gamble",
                "Gossip",
                "Haggle",
            ],
            "talents": [
                "Alley Cat",
                "Beneath Notice",
                "Etiquette (Servants)",
                "Sturdy",
            ],
            "trappings": [
                "Lodgings",
                "Sturdy Boots",
            ],
        },
    },
    "Watchman": {
        "class": "Burghers",
        "Watch Recruit": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Weapon Skill", "Strength", "Fellowship"],
            "skills": [
                "Athletics",
                "Climb",
                "Consume Alcohol",
                "Dodge",
                "Endurance",
                "Gamble",
                "Melee (Any)",
                "Perception",
            ],
            "talents": [
                "Drilled",
                "Hardy",
                "Strike to Stun",
                "Tenacious",
            ],
            "trappings": [
                "Hand Weapon",
                "Leather Jack",
                "Uniform",
            ],
        },
    },
    # Courtiers
    "Advisor": {
        "class": "Courtiers",
        "Aide": {
            "status": {"tier": "Silver", "standing": 2},
            "attributes": ["Toughness", "Initiative", "Agility"],
            "skills": [
                "Bribery",
                "Consume Alcohol",
                "Endurance",
                "Gossip",
                "Haggle",
                "Language (Classical)",
                "Lore (Politics)",
                "Perception",
            ],
            "talents": [
                "Beneath Notice",
                "Etiquette (Any)",
                "Gregarious",
                "Read/Write",
            ],
            "trappings": [
                "Writing Kit",
            ],
        },
    },
    "Artist": {
        "class": "Courtiers",
        "Apprentice Artist": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Strength", "Initiative", "Dexterity"],
            "skills": [
                "Art (Any)",
                "Cool",
                "Consume Alcohol",
                "Evaluate",
                "Endurance",
                "Gossip",
                "Perception",
                "Stealth (Urban)",
            ],
            "talents": [
                "Artistic",
                "Sharp",
                "Strong Back",
                "Tenacious",
            ],
            "trappings": [
                "Brush or Chisel or Quill Pen",
            ],
        },
    },
    "Duellist": {
        "class": "Courtiers",
        "Fencer": {
            "status": {"tier": "Silver", "standing": 3},
            "attributes": ["Weapon Skill", "Initiative", "Dexterity"],
            "skills": [
                "Athletics",
                "Dodge",
                "Endurance",
                "Heal",
                "Intuition",
                "Language (Classical)",
                "Melee (Any)",
                "Perception",
            ],
            "talents": [
                "Beat Blade",
                "Distract",
                "Feint",
                "Step Aside",
            ],
            "trappings": [
                "Hand Weapon or Rapier",
                "Sling Bag containing Clothing",
                f"{roll_d10()} Bandages",
            ],
        },
    },
    "Envoy": {
        "class": "Courtiers",
        "Herald": {
            "status": {"tier": "Silver", "standing": 2},
            "attributes": ["Toughness", "Agility", "Fellowship"],
            "skills": [
                "Athletics",
                "Charm",
                "Drive",
                "Dodge",
                "Endurance",
                "Intuition",
                "Ride (Horse)",
                "Row",
            ],
            "talents": [
                "Blather",
                "Etiquette (Nobles)",
                "Read/Write",
                "Suave",
            ],
            "trappings": [
                "Leather Jack",
                "Livery",
                "Scroll Case",
            ],
        },
    },
    "Noble": {
        "class": "Courtiers",
        "Scion": {
            "status": {"tier": "Gold", "standing": 1},
            "attributes": ["Weapon Skill", "Initiative", "Dexterity"],
            "skills": [
                "Bribery",
                "Consume Alcohol",
                "Gamble",
                "Intimidate",
                "Leadership",
                "Lore (Heraldry)",
                "Melee (Fencing)",
                "Play (Any)",
            ],
            "talents": [
                "Etiquette (Nobles)",
                "Luck",
                "Noble Blood",
                "Read/Write",
            ],
            "trappings": [
                "Courtly Garb",
                "Foil or Hand Mirror",
                f"Jewellery worth {roll_3d10()} GC",
                "Personal Servant",
            ],
        },
    },
    "Servant": {
        "class": "Courtiers",
        "Menial": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Strength", "Toughness", "Agility"],
            "skills": [
                "Athletics",
                "Climb",
                "Drive",
                "Dodge",
                "Endurance",
                "Intuition",
                "Perception",
                "Stealth (Any)",
            ],
            "talents": [
                "Beneath Notice",
                "Strong Back",
                "Strong-minded",
                "Sturdy",
            ],
            "trappings": [
                "Floor Brush",
            ],
        },
    },
    "Spy": {
        "class": "Courtiers",
        "Informer": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Agility", "Willpower", "Fellowship"],
            "skills": [
                "Bribery",
                "Charm",
                "Cool",
                "Gamble",
                "Gossip",
                "Haggle",
                "Perception",
                "Stealth (Any)",
            ],
            "talents": [
                "Blather",
                "Carouser",
                "Gregarious",
                "Shadow",
            ],
            "trappings": [
                "Charcoal stick",
                "Sling Bag containing 2 different sets of clothing and Hooded Cloak",
            ],
        },
    },
    "Warden": {
        "class": "Courtiers",
        "Custodian": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Strength", "Toughness", "Willpower"],
            "skills": [
                "Athletics",
                "Charm Animal",
                "Consume Alcohol",
                "Cool",
                "Endurance",
                "Intuition",
                "Lore (Local)",
                "Perception",
            ],
            "talents": [
                "Menacing",
                "Night Vision",
                "Sharp",
                "Strike to Stun",
            ],
            "trappings": [
                "Keys",
                "Lantern",
                "Lamp Oil",
                "Livery",
            ],
        },
    },
    # Peasants
    "Bailiff": {
        "class": "Peasants",
        "Tax Collector": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Weapon Skill", "Initiative", "Willpower"],
            "skills": [
                "Cool",
                "Dodge",
                "Endurance",
                "Gossip",
                "Haggle",
                "Intimidate",
                "Melee (Basic)",
                "Perception",
            ],
            "talents": [
                "Embezzle",
                "Numismatics",
                "Strong Back",
                "Tenacious",
            ],
            "trappings": [
                "Hand weapon",
                "small lock box",
            ],
        },
    },
    "Hedge Witch": {
        "class": "Peasants",
        "Hedge Apprentice": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Toughness", "Initiative", "Dexterity"],
            "skills": [
                "Channelling",
                "Endurance",
                "Intuition",
                "Language (Magick)",
                "Lore (Folklore)",
                "Lore (Herbs)",
                "Outdoor Survival",
                "Perception",
            ],
            "talents": [
                "Fast Hands",
                "Petty Magic",
                "Rover",
                "Strider (Woodlands)",
            ],
            "trappings": [
                f"{roll_d10()} Lucky Charms",
                "Quarterstaff",
                "Backpack",
            ],
        },
    },
    "Herbalist": {
        "class": "Peasants",
        "Herb Gatherer": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Toughness", "Initiative", "Agility"],
            "skills": [
                "Charm Animal",
                "Climb",
                "Endurance",
                "Lore (Herbs)",
                "Outdoor Survival",
                "Perception",
                "Swim",
                "Trade (Herbalist)",
            ],
            "talents": [
                "Acute Sense (Taste)",
                "Orientation",
                "Rover",
                "Strider (any)",
            ],
            "trappings": [
                "Boots",
                "Cloak",
                "Sling Bag containing Assortment of Herbs",
            ],
        },
    },
    "Hunter": {
        "class": "Peasants",
        "Trapper": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Strength", "Toughness", "Dexterity"],
            "skills": [
                "Charm Animal",
                "Climb",
                "Endurance",
                "Lore (Beasts)",
                "Outdoor Survival",
                "Perception",
                "Ranged (Sling)",
                "Set Trap",
            ],
            "talents": [
                "Hardy",
                "Rover",
                "Strider (any)",
                "Trapper",
            ],
            "trappings": [
                "Selection of Animal Traps",
                "Hand Weapon",
                "Sling with 10 Stone Bullets",
                "Sturdy Boots and Cloak",
            ],
        },
    },
    "Miner": {
        "class": "Peasants",
        "Prospector": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Strength", "Toughness", "Dexterity"],
            "skills": [
                "Cool",
                "Endurance",
                "Intuition",
                "Lore (Local)",
                "Melee (Two-handed)",
                "Outdoor Survival",
                "Perception",
                "Swim",
            ],
            "talents": [
                "Rover",
                "Strider (Rocky)",
                "Sturdy",
                "Tenacious",
            ],
            "trappings": [
                "Charcoal Stick",
                "Crude Map",
                "Pan",
                "Spade",
            ],
        },
    },
    "Mystic": {
        "class": "Peasants",
        "Fortune Teller": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Initiative", "Dexterity", "Fellowship"],
            "skills": [
                "Charm",
                "Entertain (Fortune Telling)",
                "Dodge",
                "Gossip",
                "Haggle",
                "Intuition",
                "Perception",
                "Sleight of Hand",
            ],
            "talents": [
                "Attractive",
                "Luck",
                "Second Sight",
                "Suave",
            ],
            "trappings": [
                "Deck of Cards or Dice",
                "Cheap Jewellery",
            ],
        },
    },
    "Scout": {
        "class": "Peasants",
        "Guide": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Toughness", "Initiative", "Agility"],
            "skills": [
                "Charm Animal",
                "Climb",
                "Endurance",
                "Gossip",
                "Lore (Local)",
                "Melee (Basic)",
                "Outdoor Survival",
                "Perception",
            ],
            "talents": [
                "Orientation",
                "Rover",
                "Sharp",
                "Strider (any)",
            ],
            "trappings": [
                "Hand Weapon",
                "Leather Jack",
                "Sturdy Boots and Cloak",
                "Rope",
            ],
        },
    },
    "Villager": {
        "class": "Peasants",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["Strength", "Toughness", "Agility"],
            "skills": [
                "Animal Care",
                "Athletics",
                "Consume Alcohol",
                "Endurance",
                "Gossip",
                "Melee (Brawling)",
                "Lore (Local)",
                "Outdoor Survival",
            ],
            "talents": [
                "Rover",
                "Strong Back",
                "Strong-minded",
                "Stone Soup",
            ],
            "trappings": [],
        },
    },
    # Rangers
    "Bounty Hunter": {
        "class": "Rangers",
        "Thief-taker": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Weapon Skill", "Toughness", "Agility"],
            "skills": [
                "Bribery",
                "Charm",
                "Gossip",
                "Haggle",
                "Intuition",
                "Melee (Basic)",
                "Outdoor Survival",
                "Perception",
            ],
            "talents": [
                "Break and Enter",
                "Shadow",
                "Strike to Stun",
                "Suave",
            ],
            "trappings": [
                "Hand Weapon",
                "Leather Jerkin",
                "Rope",
            ],
        },
    },
    "Coachman": {
        "class": "Rangers",
        "Postilion": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Ballistic Skill", "Toughness", "Willpower"],
            "skills": [
                "Animal Care",
                "Charm Animal",
                "Climb",
                "Drive",
                "Endurance",
                "Perception",
                "Ranged (Entangling)",
                "Ride (Horse)",
            ],
            "talents": [
                "Animal Affinity",
                "Seasoned Traveller",
                "Trick-Riding",
                "Tenacious",
            ],
            "trappings": [
                "Warm Coat and Gloves",
                "Whip",
            ],
        },
    },
    "Entertainer": {
        "class": "Rangers",
        "Busker": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Agility", "Dexterity", "Fellowship"],
            "skills": [
                "Athletics",
                "Charm",
                "Entertain (Any)",
                "Gossip",
                "Haggle",
                "Perform (Any)",
                "Play (any)",
                "Sleight of Hand",
            ],
            "talents": [
                "Attractive",
                "Mimic",
                "Public-Speaking",
                "Suave",
            ],
            "trappings": [
                "Bowl",
                "Instrument",
            ],
        },
    },
    "Flagellant": {
        "class": "Rangers",
        "Zealot": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["Weapon Skill", "Strength", "Toughness"],
            "skills": [
                "Dodge",
                "Endurance",
                "Heal",
                "Intimidate",
                "Intuition",
                "Lore (Sigmar)",
                "Melee (Flail)",
                "Outdoor Survival",
            ],
            "talents": [
                "Berserk Charge",
                "Frenzy",
                "Read/Write",
                "Stone Soup",
            ],
            "trappings": [
                "Flail",
                "Tattered Robes",
            ],
        },
    },
    "Messenger": {
        "class": "Rangers",
        "Runner": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Toughness", "Initiative", "Agility"],
            "skills": [
                "Athletics",
                "Climb",
                "Dodge",
                "Endurance",
                "Gossip",
                "Navigation",
                "Perception",
                "Melee (Brawling)",
            ],
            "talents": [
                "Flee!",
                "Fleet Footed",
                "Sprinter",
                "Step Aside",
            ],
            "trappings": [
                "Scroll Case",
            ],
        },
    },
    "Pedlar": {
        "class": "Rangers",
        "Vagabond": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Toughness", "Dexterity", "Willpower"],
            "skills": [
                "Charm",
                "Endurance",
                "Entertain (Storytelling)",
                "Gossip",
                "Haggle",
                "Intuition",
                "Outdoor Survival",
                "Stealth (Rural or Urban)",
            ],
            "talents": [
                "Fisherman",
                "Flee!",
                "Rover",
                "Tinker",
            ],
            "trappings": [
                "Backpack",
                "Bedroll",
                f"Goods worth {roll_2d10()} Brass",
                "Tent",
            ],
        },
    },
    "Road Warden": {
        "class": "Rangers",
        "Toll Keeper": {
            "status": {"tier": "Brass", "standing": 5},
            "attributes": ["Ballistic Skill", "Toughness", "Initiative"],
            "skills": [
                "Bribery",
                "Consume Alcohol",
                "Gamble",
                "Gossip",
                "Haggle",
                "Melee (Basic)",
                "Perception",
                "Ranged (Crossbow)",
            ],
            "talents": [
                "Coolheaded",
                "Embezzle",
                "Marksman",
                "Numismatics",
            ],
            "trappings": [
                "Crossbow with 10 Bolts",
                "Leather Jack",
            ],
        },
    },
    "Witch Hunter": {
        "class": "Rangers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["Weapon Skill", "Toughness", "Willpower"],
            "skills": [
                "Charm",
                "Consume Alcohol",
                "Heal",
                "Intimidate",
                "Intuition",
                "Lore (Torture)",
                "Melee (Brawling)",
                "Perception",
            ],
            "talents": [
                "Coolheaded",
                "Menacing",
                "Read/Write",
                "Resolute",
            ],
            "trappings": [
                "Hand Weapon",
                "Instruments of Torture",
            ],
        },
    },
    # Riverfolk
    "Boatman": {
        "class": "Riverfolk",
        "Boat-hand": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Strength", "Toughness", "Agility"],
            "skills": [
                "Consume Alcohol",
                "Dodge",
                "Endurance",
                "Gossip",
                "Melee (Brawling)",
                "Row",
                "Sail",
                "Swim",
            ],
            "talents": [
                "Dirty Fighting",
                "Fisherman",
                "Strong Back",
                "Strong Swimmer",
            ],
            "trappings": [
                "Hand Weapon (Boat Hook)",
                "Leather Jack",
                "Pole",
            ],
        },
    },
    "Huffer": {
        "class": "Riverfolk",
        "Riverguide": {
            "status": {"tier": "Brass", "standing": 4},
            "attributes": ["Weapon Skill", "Toughness", "Initiative"],
            "skills": [
                "Consume Alcohol",
                "Gossip",
                "Intuition",
                "Lore (Local)",
                "Lore (Riverways)",
                "Perception",
                "Row",
                "Swim",
            ],
            "talents": [
                "Fisherman",
                "Night Vision",
                "Orientation",
                "Waterman",
            ],
            "trappings": [
                "Hand Weapon (Boat Hook)",
                "Storm Lantern and Oil",
            ],
        },
    },
    "Riverwarden": {
        "class": "Riverfolk",
        "River Recruit": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Ballistic Skill", "Strength", "Fellowship"],
            "skills": [
                "Athletics",
                "Dodge",
                "Endurance",
                "Melee (Basic)",
                "Perception",
                "Row",
                "Sail",
                "Swim",
            ],
            "talents": [
                "Strong Swimmer",
                "Strong Back",
                "Very Strong",
                "Waterman",
            ],
            "trappings": [
                "Hand Weapon (Sword)",
                "Leather Jack",
                "Uniform",
            ],
        },
    },
    "Riverwoman": {
        "class": "Riverfolk",
        "Greenfish": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Toughness", "Agility", "Dexterity"],
            "skills": [
                "Athletics",
                "Consume Alcohol",
                "Dodge",
                "Endurance",
                "Gossip",
                "Outdoor Survival",
                "Row",
                "Swim",
            ],
            "talents": [
                "Fisherman",
                "Gregarious",
                "Strider (Marshes)",
                "Strong Swimmer",
            ],
            "trappings": [
                "Bucket",
                "Fishing Rod and Bait",
                "Leather Leggings",
            ],
        },
    },
    "Seaman": {
        "class": "Riverfolk",
        "Landsman": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Agility", "Dexterity", "Fellowship"],
            "skills": [
                "Climb",
                "Consume Alcohol",
                "Gamble",
                "Gossip",
                "Row",
                "Melee (Brawling)",
                "Sail",
                "Swim",
            ],
            "talents": [
                "Fisherman",
                "Strider (Coastal)",
                "Strong Back",
                "Strong Swimmer",
            ],
            "trappings": [
                "Bucket",
                "Brush",
                "Mop",
            ],
        },
    },
    "Smuggler": {
        "class": "Riverfolk",
        "River Runner": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Agility", "Dexterity", "Willpower"],
            "skills": [
                "Athletics",
                "Bribery",
                "Cool",
                "Consume Alcohol",
                "Row",
                "Sail",
                "Stealth (Rural or Urban)",
                "Swim",
            ],
            "talents": [
                "Criminal",
                "Fisherman",
                "Strider (Marshes)",
                "Strong Back",
            ],
            "trappings": [
                "Large Sack",
                "Mask or Scarves",
                "Tinderbox",
                "Storm Lantern and Oil",
            ],
        },
    },
    "Stevedore": {
        "class": "Riverfolk",
        "Dockhand": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Weapon Skill", "Toughness", "Initiative"],
            "skills": [
                "Athletics",
                "Climb",
                "Consume Alcohol",
                "Dodge",
                "Endurance",
                "Gossip",
                "Melee (Basic)",
                "Swim",
            ],
            "talents": [
                "Dirty Fighting",
                "Strong Back",
                "Sturdy",
                "Very Strong",
            ],
            "trappings": [
                "Hand Weapon (Boat Hook)",
                "Leather Gloves",
            ],
        },
    },
    "Wrecker": {
        "class": "Riverfolk",
        "Cargo Scavenger": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Weapon Skill", "Strength", "Initiative"],
            "skills": [
                "Climb",
                "Consume Alcohol",
                "Dodge",
                "Endurance",
                "Row",
                "Melee (Basic)",
                "Outdoor Survival",
                "Swim",
            ],
            "talents": [
                "Break and Enter",
                "Criminal",
                "Fisherman",
                "Strong Back",
            ],
            "trappings": [
                "Crowbar",
                "Large Sack",
                "Leather Gloves",
            ],
        },
    },
    # Rogues
    "Bawd": {
        "class": "Rogues",
        "Hustler": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Agility", "Dexterity", "Fellowship"],
            "skills": [
                "Bribery",
                "Charm",
                "Consume Alcohol",
                "Entertain (Any)",
                "Gamble",
                "Gossip",
                "Haggle",
                "Intimidate",
            ],
            "talents": [
                "Attractive",
                "Alley Cat",
                "Blather",
                "Gregarious",
            ],
            "trappings": [
                "Flask of Spirits",
            ],
        },
    },
    "Charlatan": {
        "class": "Rogues",
        "Swindler": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Initiative", "Dexterity", "Fellowship"],
            "skills": [
                "Bribery",
                "Consume Alcohol",
                "Charm",
                "Entertain (Storytelling)",
                "Gamble",
                "Gossip",
                "Haggle",
                "Sleight of Hand",
            ],
            "talents": [
                "Cardsharp",
                "Diceman",
                "Etiquette (Any)",
                "Luck",
            ],
            "trappings": [
                "Backpack",
                "2 Sets of Clothing",
                "Deck of Cards",
                "Dice",
            ],
        },
    },
    "Fence": {
        "class": "Rogues",
        "Broker": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Initiative", "Agility", "Fellowship"],
            "skills": [
                "Charm",
                "Consume Alcohol",
                "Dodge",
                "Evaluate",
                "Gamble",
                "Gossip",
                "Haggle",
                "Melee (Basic)",
            ],
            "talents": [
                "Alley Cat",
                "Cardsharp",
                "Dealmaker",
                "Gregarious",
            ],
            "trappings": [
                "Hand Weapon",
                f"Stolen Goods worth {roll_3d10()} Shillings",
            ],
        },
    },
    "Grave Robber": {
        "class": "Rogues",
        "Body Snatcher": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Strength", "Initiative", "Willpower"],
            "skills": [
                "Climb",
                "Cool",
                "Dodge",
                "Endurance",
                "Gossip",
                "Intuition",
                "Perception",
                "Stealth (Any)",
            ],
            "talents": [
                "Alley Cat",
                "Criminal",
                "Flee!",
                "Strong Back",
            ],
            "trappings": [
                "Crowbar",
                "Handcart",
                "Hooded Cloak",
                "Tarpaulin",
            ],
        },
    },
    "Outlaw": {
        "class": "Rogues",
        "Brigand": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Weapon Skill", "Strength", "Toughness"],
            "skills": [
                "Athletics",
                "Consume Alcohol",
                "Cool",
                "Endurance",
                "Gamble",
                "Intimidate",
                "Melee (Basic)",
                "Outdoor Survival",
            ],
            "talents": [
                "Combat Aware",
                "Criminal",
                "Rover",
                "Flee!",
            ],
            "trappings": [
                "Bedroll",
                "Hand Weapon",
                "Leather Jerkin",
                "Tinderbox",
            ],
        },
    },
    "Racketeer": {
        "class": "Rogues",
        "Thug": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Weapon Skill", "Strength", "Toughness"],
            "skills": [
                "Consume Alcohol",
                "Cool",
                "Dodge",
                "Endurance",
                "Intimidate",
                "Lore (Local)",
                "Melee (Brawling)",
                "Stealth (Urban)",
            ],
            "talents": [
                "Criminal",
                "Etiquette (Criminals)",
                "Menacing",
                "Strike Mighty Blow",
            ],
            "trappings": [
                "Knuckledusters",
                "Leather Jack",
                "",
            ],
        },
    },
    "Thief": {
        "class": "Rogues",
        "Prowler": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Initiative", "Agility", "Willpower"],
            "skills": [
                "Athletics",
                "Climb",
                "Cool",
                "Dodge",
                "Endurance",
                "Intuition",
                "Perception",
                "Stealth (Urban)",
            ],
            "talents": [
                "Alley Cat",
                "Criminal",
                "Flee!",
                "Strike to Stun",
            ],
            "trappings": [
                "Crowbar",
                "Leather Jerkin",
                "Sack",
            ],
        },
    },
    "Witch": {
        "class": "Rogues",
        "": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Weapon Skill", "Toughness", "Willpower"],
            "skills": [
                "Channelling",
                "Cool",
                "Endurance",
                "Gossip",
                "Intimidate",
                "Language (Magick)",
                "Sleight of Hand",
                "Stealth (Rural)",
            ],
            "talents": [
                "Criminal",
                "Instinctive Diction",
                "Menacing",
                "Petty Magic",
            ],
            "trappings": [
                "Candles",
                "Chalk",
                "Doll",
                "Pins",
            ],
        },
    },
    # Warriors
    "Cavalryman": {
        "class": "Warriors",
        "Horseman": {
            "status": {"tier": "Silver", "standing": 2},
            "attributes": ["Weapon Skill", "Strength", "Agility"],
            "skills": [
                "Animal Care",
                "Charm Animal",
                "Endurance",
                "Language (Battle)",
                "Melee (Basic)",
                "Outdoor Survival",
                "Perception",
                "Ride (Horse)",
            ],
            "talents": [
                "Combat Aware",
                "Crack the Whip",
                "Lightning Reflexes",
                "Roughrider",
            ],
            "trappings": [
                "Leather Jack",
                "Riding Horse with Saddle and Tack",
            ],
        },
    },
    "Guard": {
        "class": "Warriors",
        "Sentry": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Weapon Skill", "Toughness", "Agility"],
            "skills": [
                "Consume Alcohol",
                "Endurance",
                "Entertain (Storytelling)",
                "Gamble",
                "Gossip",
                "Intuition",
                "Melee (Basic)",
                "Perception",
            ],
            "talents": [
                "Diceman",
                "Etiquette (Servants)",
                "Strike to Stun",
                "Tenacious",
            ],
            "trappings": [
                "Buckler",
                "Leather Jerkin",
                "Storm Lantern with Oil",
            ],
        },
    },
    "Knight": {
        "class": "Warriors",
        "": {
            "status": {"tier": "Silver", "standing": 3},
            "attributes": ["Strength", "Initiative", "Agility"],
            "skills": [
                "Athletics",
                "Animal Care",
                "Charm Animal",
                "Heal",
                "Lore (Heraldry)",
                "Melee (Cavalry)",
                "Ride (Horse)",
                "Trade (Farrier)",
            ],
            "talents": [
                "Etiquette (any)",
                "Roughrider",
                "Sturdy",
                "Warrior Born",
            ],
            "trappings": [
                "Leather Jack",
                "Mail Shirt",
                "Riding Horse with Saddle and Tack",
                "Shield",
                "Trade Tools (Farrier)",
            ],
        },
    },
    "Pit Fighter": {
        "class": "Warriors",
        "Pugilist": {
            "status": {"tier": "Brass", "standing": 4},
            "attributes": ["Weapon Skill", "Strength", "Toughness"],
            "skills": [
                "Athletics",
                "Cool",
                "Dodge",
                "Endurance",
                "Gamble",
                "Intimidate",
                "Melee (Any)",
                "Melee (Brawling)",
            ],
            "talents": [
                "Dirty Fighting",
                "In-fighter",
                "Iron Jaw",
                "Reversal",
            ],
            "trappings": [
                "Bandages",
                "Knuckledusters",
                "Leather Jack",
            ],
        },
    },
    "Protagonist": {
        "class": "Warriors",
        "Braggart": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Weapon Skill", "Toughness", "Agility"],
            "skills": [
                "Athletics",
                "Dodge",
                "Endurance",
                "Entertain (Taunt)",
                "Gossip",
                "Haggle",
                "Intimidate",
                "Melee (Any)",
            ],
            "talents": [
                "In-fighter",
                "Dirty Fighting",
                "Menacing",
                "Warrior Born",
            ],
            "trappings": [
                "Hood or Mask",
                "Knuckledusters",
                "Leather Jack",
            ],
        },
    },
    "Slayer": {
        "class": "Warriors",
        "Troll Slayer": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Weapon Skill", "Strength", "Willpower"],
            "skills": [
                "Consume Alcohol",
                "Cool",
                "Dodge",
                "Endurance",
                "Gamble",
                "Heal",
                "Lore (Trolls)",
                "Melee (Basic)",
            ],
            "talents": [
                "Dual Wielder",
                "Fearless (Everything)",
                "Frenzy",
                "Slayer",
            ],
            "trappings": [
                "Axe",
                "Flask of Spirits",
                "Shame",
                "Tattoos",
            ],
        },
    },
    "Soldier": {
        "class": "Warriors",
        "Recruit": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Weapon Skill", "Toughness", "Willpower"],
            "skills": [
                "Athletics",
                "Climb",
                "Cool",
                "Dodge",
                "Endurance",
                "Language (Battle)",
                "Melee (Basic)",
                "Play (Drum or Fife)",
            ],
            "talents": [
                "Diceman",
                "Marksman",
                "Strong Back",
                "Warrior Born",
            ],
            "trappings": [
                "Dagger",
                "Leather Breastplate",
                "Uniform",
            ],
        },
    },
    "Warrior Priest": {
        "class": "Warriors",
        "Novitiate": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Weapon Skill", "Toughness", "Willpower"],
            "skills": [
                "Cool",
                "Dodge",
                "Endurance",
                "Heal",
                "Leadership",
                "Lore (Theology)",
                "Melee (Any)",
                "Pray",
            ],
            "talents": [
                "Bless (Any)",
                "Etiquette (Cultists)",
                "Read/Write",
                "Strong-minded",
            ],
            "trappings": [
                "Book (Religion)",
                "Leather Jerkin",
                "Religious Symbol",
                "Robes",
                "Weapon (Any Melee)",
            ],
        },
    },
}
