from wfrp.character.utils import roll_3d10
from wfrp.character.utils import roll_d10


def list_careers(species=None):
    if species is None:
        return list(CAREER_DATA.keys())
    if species == "Human":
        return list(HUMAN_CAREERS.values())
    elif species == "Halfling":
        return list(HALFLING_CAREERS.values())
    elif species == "Dwarf":
        return list(DWARF_CAREERS.values())
    elif species == "High Elf":
        return list(HIGH_ELF_CAREERS.values())
    elif species == "Wood Elf":
        return list(WOOD_ELF_CAREERS.values())
    raise NotImplementedError("Invalid species sent to list careers")


def get_career(species, die_roll):
    if species == "Human":
        career_list = HUMAN_CAREERS
    elif species == "Halfling":
        career_list = HALFLING_CAREERS
    elif species == "Dwarf":
        career_list = DWARF_CAREERS
    elif species == "High Elf":
        career_list = HIGH_ELF_CAREERS
    elif species == "Wood Elf":
        career_list = WOOD_ELF_CAREERS
    else:
        raise NotImplementedError("Invalid species sent to get career")
    while True:
        try:
            return career_list[die_roll]
        except KeyError:
            die_roll += 1


CAREER_DATA = {
    # Academics
    "Apothecary": {
        "class": "Academics",
        "Apothecary’s Apprentice": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Toughness", "Dexterity", "Intelligence"],
            "skills": [
                "Consume Alcohol",
                "Heal",
                "Language (Classical)",
                "Lore (Chemistry)",
                "Lore (Medicine)",
                "Lore (Plants)",
                "Trade (Apothecary)",
                "Trade (Poisoner)",
            ],
            "talents": [
                "Concoct",
                "Craftsman (Apothecary)",
                "Etiquette (Scholar)",
                "Read/Write",
            ],
            "trappings": [
                "Book (Blank)",
                "Healing Draught",
                "Leather Jerkin",
                "Pestle and Mortar",
            ],
        },
    },
    "Engineer": {
        "class": "Academics",
        "Student Engineer": {
            "status": {"tier": "Brass", "standing": 4},
            "attributes": ["Ballistic Skill", "Dexterity", "Intelligence"],
            "skills": [
                "Consume Alcohol",
                "Cool",
                "Endurance",
                "Language (Classical)",
                "Lore (Engineer)",
                "Perception",
                "Ranged (Blackpowder)",
                "Trade (Engineer)",
            ],
            "talents": [
                "Artistic",
                "Gunner",
                "Read/Write",
                "Tinker",
            ],
            "trappings": [
                "Book (Engineer)",
                "Hammer and Spikes",
            ],
        },
    },
    "Lawyer": {
        "class": "Academics",
        "Student Lawyer": {
            "status": {"tier": "Brass", "standing": 4},
            "attributes": ["Initiative", "Dexterity", "Intelligence"],
            "skills": [
                "Consume Alcohol",
                "Endurance",
                "Haggle",
                "Language (Classical)",
                "Lore (Law)",
                "Lore (Theology)",
                "Perception",
                "Research",
            ],
            "talents": [
                "Blather",
                "Etiquette (Scholar)",
                "Read/Write",
                "Speedreader",
            ],
            "trappings": [
                "Book (Law)",
                "Magnifying Glass",
            ],
        },
    },
    "Nun": {
        "class": "Academics",
        "Novitiate": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Dexterity", "Intelligence", "Fellowship"],
            "skills": [
                "Art (Calligraphy)",
                "Cool",
                "Endurance",
                "Entertain (Storyteller)",
                "Gossip",
                "Heal",
                "Lore (Theology)",
                "Pray",
            ],
            "talents": [
                "Bless (Any)",
                "Stone Soup",
                "Panhandle",
                "Read/Write",
            ],
            "trappings": [
                "Religious Symbol",
                "Robes",
            ],
        },
    },
    "Physician": {
        "class": "Academics",
        "Physician’s Apprentice": {
            "status": {"tier": "Brass", "standing": 4},
            "attributes": ["Dexterity", "Intelligence", "Willpower"],
            "skills": [
                "Bribery",
                "Cool",
                "Drive",
                "Endurance",
                "Gossip",
                "Heal",
                "Perception",
                "Sleight of Hand",
            ],
            "talents": [
                "Bookish",
                "Field Dressing",
                "Read/Write",
                "Strike to Stun",
            ],
            "trappings": [
                "Bandages",
                "Healing Draught",
            ],
        },
    },
    "Priest": {
        "class": "Academics",
        "Initiate": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Toughness", "Agility", "Willpower"],
            "skills": [
                "Athletics",
                "Cool",
                "Endurance",
                "Intuition",
                "Lore (Theology)",
                "Perception",
                "Pray",
                "Research",
            ],
            "talents": [
                "Bless (Any)",
                "Holy Visions",
                "Read/Write",
                "Suave",
            ],
            "trappings": [
                "Religious Symbol",
                "Robes",
            ],
        },
    },
    "Scholar": {
        "class": "Academics",
        "Student": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Toughness", "Intelligence", "Willpower"],
            "skills": [
                "Consume Alcohol",
                "Entertain (Storytelling)",
                "Gamble",
                "Gossip",
                "Haggle",
                "Language (Classical)",
                "Lore (Any)",
                "Research",
            ],
            "talents": [
                "Carouser",
                "Read/Write",
                "Savvy",
                "Super Numerate",
            ],
            "trappings": [
                "Alcohol",
                "Book",
                "Opinions",
                "Writing Kit",
            ],
        },
    },
    "Wizard": {
        "class": "Academics",
        "Wizard’s Apprentice": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Weapon Skill", "Intelligence", "Willpower"],
            "skills": [
                "Channelling (Any Colour)",
                "Dodge",
                "Intuition",
                "Language (Magick)",
                "Lore (Magic)",
                "Melee (Basic)",
                "Melee (Polearm)",
                "Perception",
            ],
            "talents": [
                "Aethyric Attunement",
                "Petty Magic",
                "Read/Write",
                "Second Sight",
            ],
            "trappings": [
                "Grimoire",
                "Quarterstaff",
            ],
        },
    },
    # Burghers
    "Agitator": {
        "class": "Burghers",
        "Pamphleteer": {
            "status": {"tier": "Brass", "standing": 1},
            "attributes": ["Ballistic Skill", "Intelligence", "Fellowship"],
            "skills": [
                "Art (Writing)",
                "Bribery",
                "Charm",
                "Consume Alcohol",
                "Gossip",
                "Haggle",
                "Lore (Politics)",
                "Trade (Printing)",
            ],
            "talents": [
                "Blather",
                "Gregarious",
                "Panhandle",
                "Read/Write",
            ],
            "trappings": [
                "Writing Kit",
                "Hammer and Nails",
                "Pile of Leaflets",
            ],
        },
    },
    "Artisan": {
        "class": "Burghers",
        "Apprentice Artisan": {
            "status": {"tier": "Brass", "standing": 2},
            "attributes": ["Strength", "Toughness", "Dexterity"],
            "skills": [
                "Athletics",
                "Cool",
                "Consume Alcohol",
                "Dodge",
                "Endurance",
                "Evaluate",
                "Stealth (Urban)",
                "Trade (Any)",
            ],
            "talents": [
                "Artistic",
                "Craftsman (any)",
                "Strong Back",
                "Very Strong",
            ],
            "trappings": [
                "Chalk",
                "Leather Jerkin",
                f"{roll_d10()} rags",
            ],
        },
    },
    "Beggar": {
        "class": "Burghers",
        "Pauper": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["Toughness", "Agility", "Fellowship"],
            "skills": [
                "Athletics",
                "Charm",
                "Consume Alcohol",
                "Cool",
                "Dodge",
                "Endurance",
                "Intuition",
                "Stealth (Urban)",
            ],
            "talents": [
                "Panhandle",
                "Resistance (Disease)",
                "Stone Soup",
                "Very Resilient",
            ],
            "trappings": [
                "Poor Quality Blanket",
                "Cup",
            ],
        },
    },
    "Investigator": {
        "class": "Burghers",
        "Sleuth": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["", "", ""],
            "skills": [
                "Charm",
                "Climb",
                "Cool",
                "Gossip",
                "Intuition",
                "Perception",
                "Stealth (Urban)",
                "Track",
            ],
            "talents": [
                "Alley Cat",
                "Beneath Notice",
                "Read/Write",
                "Sharp",
            ],
            "trappings": [
                "Lantern",
                "Lamp Oil,",
                "Journal",
                "Quill and Ink",
            ],
        },
    },
    "Merchant": {
        "class": "Burghers",
        "Trader": {
            "status": {"tier": "Silver", "standing": 2},
            "attributes": ["Agility", "Willpower", "Fellowship"],
            "skills": [
                "Animal Care",
                "Bribery",
                "Charm",
                "Consume Alcohol",
                "Drive",
                "Gamble",
                "Gossip",
                "Haggle",
            ],
            "talents": [
                "Blather",
                "Dealmaker",
                "Read/Write",
                "Suave",
            ],
            "trappings": [
                "Abacus",
                "Mule and Cart",
                "Canvas Tarpaulin",
                f"{roll_3d10()} Silver Shillings",
            ],
        },
    },
    "Rat Catcher": {
        "class": "Burghers",
        "Rat Hunter": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Weapon Skill", "Ballistic Skill", "Willpower"],
            "skills": [
                "Athletics",
                "Animal Training (Dog)",
                "Charm Animal",
                "Consume Alcohol",
                "Endurance",
                "Melee (Basic)",
                "Ranged (Sling)",
                "Stealth (Underground or Urban)",
            ],
            "talents": [
                "Night Vision",
                "Resistance (Disease)",
                "Strike Mighty Blow",
                "Strike to Stun",
            ],
            "trappings": [
                "Sling with Ammunition",
                "Sack",
                "Small but Vicious Dog",
            ],
        },
    },
    "Townsman": {
        "class": "Burghers",
        "Clerk": {
            "status": {"tier": "Silver", "standing": 1},
            "attributes": ["Agility", "Intelligence", "Fellowship"],
            "skills": [
                "Charm",
                "Climb",
                "Consume Alcohol",
                "Drive",
                "Dodge",
                "Gamble",
                "Gossip",
                "Haggle",
            ],
            "talents": [
                "Alley Cat",
                "Beneath Notice",
                "Etiquette (Servants)",
                "Sturdy",
            ],
            "trappings": [
                "Lodgings",
                "Sturdy Boots",
            ],
        },
    },
    "Watchman": {
        "class": "Burghers",
        "Watch Recruit": {
            "status": {"tier": "Brass", "standing": 3},
            "attributes": ["Weapon Skill", "Strength", "Fellowship"],
            "skills": [
                "Athletics",
                "Climb",
                "Consume Alcohol",
                "Dodge",
                "Endurance",
                "Gamble",
                "Melee (Any)",
                "Perception",
            ],
            "talents": [
                "Drilled",
                "Hardy",
                "Strike to Stun",
                "Tenacious",
            ],
            "trappings": [
                "Hand Weapon",
                "Leather Jack",
                "Uniform",
            ],
        },
    },
    # Courtiers
    "Advisor": {
        "class": "Courtiers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Artist": {
        "class": "Courtiers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Duellist": {
        "class": "Courtiers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Envoy": {
        "class": "Courtiers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Noble": {
        "class": "Courtiers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Servant": {
        "class": "Courtiers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Spy": {
        "class": "Courtiers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Warden": {
        "class": "Courtiers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    # Peasants
    "Bailiff": {
        "class": "Peasants",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Hedge Witch": {
        "class": "Peasants",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Herbalist": {
        "class": "Peasants",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Hunter": {
        "class": "Peasants",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Miner": {
        "class": "Peasants",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Mystic": {
        "class": "Peasants",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Scout": {
        "class": "Peasants",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Villager": {
        "class": "Peasants",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    # Rangers
    "Bounty Hunter": {
        "class": "Rangers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Coachman": {
        "class": "Rangers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Entertainer": {
        "class": "Rangers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Flagellant": {
        "class": "Rangers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Messenger": {
        "class": "Rangers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Pedlar": {
        "class": "Rangers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Road Warden": {
        "class": "Rangers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Witch Hunter": {
        "class": "Rangers",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    # Riverfolk
    "Boatman": {
        "class": "Riverfolk",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Huffer": {
        "class": "Riverfolk",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Riverwarden": {
        "class": "Riverfolk",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Riverwoman": {
        "class": "Riverfolk",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Seaman": {
        "class": "Riverfolk",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Smuggler": {
        "class": "Riverfolk",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Stevedore": {
        "class": "Riverfolk",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Wrecker": {
        "class": "Riverfolk",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    # Rogues
    "Bawd": {
        "class": "Rogues",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Charlatan": {
        "class": "Rogues",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Fence": {
        "class": "Rogues",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Grave Robber": {
        "class": "Rogues",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Outlaw": {
        "class": "Rogues",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Racketeer": {
        "class": "Rogues",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Thief": {
        "class": "Rogues",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Witch": {
        "class": "Rogues",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    # Warriors
    "Cavalryman": {
        "class": "Warriors",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Guard": {
        "class": "Warriors",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Knight": {
        "class": "Warriors",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Pit Fighter": {
        "class": "Warriors",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Protagonist": {
        "class": "Warriors",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Soldier": {
        "class": "Warriors",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Slayer": {
        "class": "Warriors",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
    "Warrior Priest": {
        "class": "Warriors",
        "": {
            "status": {"tier": "Brass", "standing": 0},
            "attributes": ["", "", ""],
            "skills": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "talents": [
                "",
                "",
                "",
                "",
            ],
            "trappings": [
                "",
                "",
                "",
            ],
        },
    },
}

# CAREERS = []

HUMAN_CAREERS = {
    1: "Apothecary",
    2: "Engineer",
    3: "Lawyer",
    5: "Nun",
    6: "Physician",
    11: "Priest",
    13: "Scholar",
    14: "Wizard",
    15: "Agitator",
    17: "Artisan",
    19: "Beggar",
    20: "Investigator",
    21: "Merchant",
    23: "Rat Catcher",
    26: "Townsman",
    27: "Watchman",
    28: "Advisor",
    29: "Artist",
    30: "Duellist",
    31: "Envoy",
    32: "Noble",
    35: "Servant",
    36: "Spy",
    37: "Warden",
    38: "Bailiff",
    39: "Hedge Witch",
    40: "Herbalist",
    42: "Hunter",
    43: "Miner",
    44: "Mystic",
    45: "Scout",
    50: "Villager",
    51: "Bounty Hunter",
    52: "Coachman",
    54: "Entertainer",
    56: "Flagellant",
    57: "Messenger",
    58: "Pedlar",
    59: "Road Warden",
    60: "Witch Hunter",
    62: "Boatman",
    63: "Huffer",
    65: "Riverwarden",
    68: "Riverwoman",
    70: "Seaman",
    71: "Smuggler",
    73: "Stevedore",
    74: "Wrecker",
    76: "Bawd",
    77: "Charlatan",
    78: "Fence",
    79: "Grave Robber",
    83: "Outlaw",
    84: "Racketeer",
    87: "Thief",
    88: "Witch",
    90: "Cavalryman",
    92: "Guard",
    93: "Knight",
    94: "Pit Fighter",
    95: "Protagonist",
    99: "Soldier",
    100: "Warrior Priest",
}

DWARF_CAREERS = {
    1: "Apothecary",
    4: "Engineer",
    6: "Lawyer",
    7: "Physician",
    9: "Scholar",
    11: "Agitator",
    17: "Artisan",
    18: "Beggar",
    20: "Investigator",
    24: "Merchant",
    25: "Rat Catcher",
    31: "Townsman",
    34: "Watchman",
    36: "Advisor",
    37: "Artist",
    38: "Duellist",
    40: "Envoy",
    41: "Noble",
    42: "Servant",
    43: "Spy",
    45: "Warden",
    47: "Bailiff",
    49: "Hunter",
    54: "Miner",
    55: "Scout",
    56: "Villager",
    60: "Bounty Hunter",
    61: "Coachman",
    63: "Entertainer",
    65: "Messenger",
    67: "Pedlar",
    69: "Boatman",
    70: "Huffer",
    72: "Riverwoman",
    73: "Seaman",
    75: "Smuggler",
    77: "Stevedore",
    78: "Wrecker",
    79: "Fence",
    82: "Outlaw",
    83: "Racketeer",
    84: "Thief",
    87: "Guard",
    90: "Pit Fighter",
    93: "Protagonist",
    96: "Soldier",
    100: "Slayer",
}

HALFLING_CAREERS = {
    1: "Apothecary",
    2: "Engineer",
    4: "Lawyer",
    6: "Physician",
    8: "Scholar",
    10: "Agitator",
    15: "Artisan",
    19: "Beggar",
    21: "Investigator",
    25: "Merchant",
    28: "Rat Catcher",
    31: "Townsman",
    33: "Watchman",
    34: "Advisor",
    36: "Artist",
    37: "Envoy",
    43: "Servant",
    44: "Spy",
    46: "Warden",
    47: "Bailiff",
    50: "Herbalist",
    52: "Hunter",
    53: "Miner",
    54: "Scout",
    57: "Villager",
    58: "Bounty Hunter",
    60: "Coachman",
    63: "Entertainer",
    65: "Messenger",
    67: "Pedlar",
    68: "Road Warden",
    69: "Boatman",
    70: "Huffer",
    71: "Riverwarden",
    74: "Riverwoman",
    75: "Seaman",
    79: "Smuggler",
    82: "Stevedore",
    85: "Bawd",
    86: "Charlatan",
    87: "Fence",
    88: "Grave Robber",
    89: "Outlaw",
    90: "Racketeer",
    94: "Thief",
    96: "Guard",
    97: "Pit Fighter",
    100: "Soldier",
}

HIGH_ELF_CAREERS = {
    2: "Apothecary",
    6: "Lawyer",
    8: "Physician",
    12: "Scholar",
    16: "Wizard",
    19: "Artisan",
    21: "Investigator",
    26: "Merchant",
    28: "Townsman",
    29: "Watchman",
    31: "Advisor",
    32: "Artist",
    34: "Duellist",
    37: "Envoy",
    40: "Noble",
    43: "Spy",
    45: "Warden",
    47: "Herbalist",
    50: "Hunter",
    56: "Scout",
    59: "Bounty Hunter",
    62: "Entertainer",
    63: "Messenger",
    64: "Boatman",
    79: "Seaman",
    80: "Smuggler",
    82: "Bawd",
    85: "Charlatan",
    88: "Outlaw",
    92: "Cavalryman",
    94: "Guard",
    95: "Knight",
    97: "Pit Fighter",
    98: "Protagonist",
    100: "Soldier",
}

WOOD_ELF_CAREERS = {
    1: "Scholar",
    5: "Wizard",
    10: "Artisan",
    14: "Advisor",
    18: "Artist",
    25: "Envoy",
    31: "Noble",
    35: "Spy",
    42: "Herbalist",
    52: "Hunter",
    57: "Mystic",
    68: "Scout",
    70: "Bounty Hunter",
    75: "Entertainer",
    78: "Messenger",
    79: "Wrecker",
    85: "Outlaw",
    90: "Cavalryman",
    92: "Guard",
    94: "Knight",
    96: "Pit Fighter",
    100: "Soldier",
}
