def includeme(config):
    config.add_route("homepage", "/")
    config.add_route("about", "/about")
    config.add_route("login", "/login")
    config.add_route("google_login", "/google")
    config.add_route("logout", "/logout")
    config.add_route("account", "/account")
    config.add_route("register", "/register")
    config.add_route("links", "/links")
    config.add_route("campaign_new", "/campaign/new")
    config.add_route("campaign_edit", "/campaign/{id}/edit")
    config.add_route("new_character", "/character/new")
    config.add_route("species", "/character/{id}/species")
    config.add_route("career", "/character/{id}/career")
    config.add_route("attributes", "/character/{id}/attributes")
    config.add_route("advances", "/character/{id}/advances")
    config.add_route("career_skills", "/character/{id}/career_skills")
    config.add_route("species_skills", "/character/{id}/species_skills")
    config.add_route("trappings", "/character/{id}/trappings")
    config.add_route("details", "/character/{id}/details")
    config.add_route("name", "/character/{id}/name")
    config.add_route("experience", "/character/{id}/experience")
    config.add_route("character_full", "/character/{id}/view")
    config.add_route("character_edit", "/character/{id}/edit")
    config.add_route("character_summary", "/character/{id}/summary")
    config.add_route("pdf_print", "/character/{id}/pdf_print")
    config.scan("wfrp.character.views")
    config.scan("wfrp.character.views.create_character")
