SPECIES_LIST = {
    "Human": {
        "skills": [
            "Animal Care",
            "Charm",
            "Cool",
            "Evaluate",
            "Gossip",
            "Haggle",
            "Language (Bretonnian)",
            "Language (Wastelander)",
            "Leadership",
            "Lore (Reikland)",
            "Melee (Basic)",
            "Ranged (Bow)",
        ],
        "talents": ["Doomed", "Savvy or Suave", "3 Random Talents"],
    },
    "Halfling": {
        "skills": [
            "Charm",
            "Consume Alcohol",
            "Dodge",
            "Gamble",
            "Haggle",
            "Intuition",
            "Language (Mootish)",
            "Lore (Reikland)",
            "Perception",
            "Sleight of Hand",
            "Stealth (Any)",
            "Trade (Cook)",
        ],
        "talents": [
            "Acute Sense (Taste)",
            "Night Vision",
            "Resistance (Chaos)",
            "Small",
            "2 Random Talents",
        ],
    },
    "Dwarf": {
        "skills": [
            "Consume Alcohol",
            "Cool",
            "Endurance",
            "Entertain (Storytelling)",
            "Evaluate",
            "Intimidate",
            "Language (Khazalid)",
            "Lore (Dwarfs)",
            "Lore (Geology)",
            "Lore (Metallurgy)",
            "Melee (Basic)",
            "Trade (any one)",
        ],
        "talents": [
            "Magic Resistance",
            "Night Vision",
            "Read/Write or Relentless",
            "Resolute or Strong-minded",
            "Sturdy",
        ],
    },
    "High Elf": {
        "skills": [
            "Cool",
            "Entertain (Sing)",
            "Evaluate",
            "Language (Eltharin)",
            "Leadership",
            "Melee (Basic)",
            "Navigation",
            "Perception",
            "Play (any one)",
            "Ranged (Bow)",
            "Sail",
            "Swim",
        ],
        "talents": [
            "Acute Sense (Sight)",
            "Coolheaded or Savvy",
            "Night Vision",
            "Second Sight or Sixth Sense",
            "Read/Write",
        ],
    },
    "Wood Elf": {
        "skills": [
            "Athletics",
            "Climb",
            "Endurance",
            "Entertain (Sing)",
            "Intimidate",
            "Language (Eltharin)",
            "Melee (Basic)",
            "Outdoor Survival",
            "Perception",
            "Ranged (Bow)",
            "Stealth (Rural)",
            "Track",
        ],
        "talents": [
            "Acute Sense (Sight)",
            "Hardy or Second Sight",
            "Night Vision",
            "Read/Write or Very Resilient",
            "Rover",
        ],
    },
}
